import { expect, test } from './fixtures/wallet';

test('Spanish dialogs create chats, edit labeled gate rules and recover from import errors', async ({ page, walletAddress }, testInfo) => {
  expect(walletAddress).toMatch(/^0x/);
  const pageErrors: string[] = []; page.on('pageerror', error => pageErrors.push(error.message));
  await page.goto('/');
  await page.locator('.nav-item', { hasText: 'Settings' }).click();
  await page.getByRole('button', { name: 'Connect wallet', exact: true }).click();
  await page.getByRole('combobox', { name: 'Language', exact: true }).selectOption('es');
  await page.locator('.nav-item', { hasText: 'Chats' }).click();
  await page.getByRole('button', { name: '+ Chat', exact: true }).click();
  const dm = page.getByRole('dialog', { name: 'Nuevo mensaje directo' });
  await dm.getByRole('textbox', { name: 'Dirección o nombre ENS', exact: false }).fill('0x000000000000000000000000000000000000dEaD');
  await dm.getByRole('textbox', { name: 'Nombre visible (opcional)' }).fill('Amiga');
  await dm.getByRole('button', { name: 'Iniciar chat' }).click();
  await expect(page.locator('.thread-title')).toContainText('Amiga');
  await page.getByRole('textbox', { name: 'Escribe un mensaje' }).fill('Hola');
  await page.getByRole('button', { name: 'Enviar', exact: true }).click();
  await expect(page.locator('.msg-time').last()).toHaveText(/^\d{2}:\d{2}$/);
  await expect(page.locator('.list-item-time').first()).toHaveText(/^\d{2}:\d{2}$/);
  await page.locator('.nav-item', { hasText: 'Salas' }).click();
  await page.getByRole('button', { name: '+ Sala' }).click();
  const room = page.getByRole('dialog', { name: 'Nueva sala' });
  await room.getByRole('textbox', { name: 'Nombre de la sala', exact: true }).fill('sala de prueba');
  await room.getByRole('button', { name: 'Token', exact: true }).click();
  const rule = room.getByRole('group', { name: 'Regla 1' });
  await rule.getByRole('combobox', { name: 'Estándar del token' }).selectOption('erc1155');
  await rule.getByRole('textbox', { name: 'Dirección del token' }).fill('0x000000000000000000000000000000000000dEaD');
  await rule.getByRole('textbox', { name: 'ID del token' }).fill('77');
  await expect(rule.getByRole('textbox', { name: 'Saldo mínimo' })).toHaveValue('1');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath('spanish-room-dialog.png'), fullPage: true });
  expect(await room.locator('.modal-body').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  expect((await rule.getByRole('combobox', { name: 'Estándar del token' }).boundingBox())!.width).toBeGreaterThan(110);
  await rule.getByRole('button', { name: 'Eliminar regla' }).click();
  await expect(room.getByText('Sin reglas = abierto a todo el mundo.')).toBeVisible();
  await room.getByRole('checkbox', { name: 'Pausar las publicaciones de miembros en Chirpy' }).check();
  await room.getByRole('button', { name: 'Crear sala' }).click();
  await expect(page.locator('.thread-title')).toContainText('sala de prueba');
  await expect(page.locator('.thread-sub')).toContainText('1 miembro · abierta · solo lectura');
  await expect(page.getByRole('navigation', { name: 'Principal' })).toBeVisible();
  await page.getByRole('button', { name: /Ajustes/ }).click();
  await page.getByRole('button', { name: 'Importar', exact: true }).click();
  const importer = page.getByRole('dialog', { name: 'Importar organización' });
  await importer.getByRole('textbox').fill('{malformed');
  await importer.getByRole('button', { name: 'Importar', exact: true }).click();
  await expect(importer.getByRole('alert')).toHaveText('JSON no válido');
  await importer.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await page.getByRole('button', { name: 'Crear', exact: true }).click();
  const creator = page.getByRole('dialog', { name: 'Crear organización' });
  await creator.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Organización nueva');
  await creator.getByRole('spinbutton', { name: 'ID de la red' }).fill('1.5');
  await creator.getByRole('button', { name: 'Crear organización', exact: true }).click();
  await expect(creator.getByRole('alert')).toContainText('chain.chainId no es válido');
  await creator.getByRole('spinbutton', { name: 'ID de la red' }).fill('1');
  await creator.getByRole('button', { name: 'Crear organización', exact: true }).click();
  await expect(creator).toHaveCount(0);
  await expect(page.locator('.org-detail')).toContainText('Organización nueva');
  expect(pageErrors).toEqual([]);
});
